endpoints:
  shutdown:
    enabled: true
management:
  security:
    enabled: false
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:5000}
wechat:
  mp:
    appId: wx8c1879e42b33b4b7
    secret: ${WECHAT_SECRET}
    token: 123456
    aesKey: utPDs4iZ5Kr1KZWvRHLrHy69IZDh9f9WKralRH04LKZ