endpoints:
  shutdown:
    enabled: true
management:
  security:
    enabled: false
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/heroku_41cd1a4394379b4?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: bb797197129266
    password: c05ba530
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8090